baseURL = 'https://alcantarajulio.github.io/'
languageCode = 'en-us'
title = 'JLI'
theme = 'terminal'
defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  contentTypeName = 'posts'
  fullWidthTheme = false 
  centerTheme = true
  showLanguageSelector = true
  authorName = 'Julio Alcantara'

[languages]
  [languages.pt]
    languageName = 'PT-BR'
    weight = 1
    title = 'Julio Alcantara'
    contentDir = 'content/pt'
    params.readMore = 'Continuar lendo'
    params.menuMore = 'Mais'
    params.readOtherPosts = 'Outros posts'
    [languages.pt.params.logo]
      logoText = 'Julio Alcantara'
      logoHomeLink = '/'

  [languages.en]
    languageName = 'EN'
    weight = 2
    title = 'Julio Alcantara'
    contentDir = 'content/en'
    params.readMore = 'Read more'
    params.menuMore = 'More'
    params.readOtherPosts = 'Other posts'
    [languages.en.params.logo]
      logoText = 'Julio Alcantara'
      logoHomeLink = '/en/'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[languages.pt.menu.main]]
  name = 'Blog'
  url  = '/blog/'
  weight = 20

  [[languages.pt.menu.main]]
    parent = 'Blog'
    name   = 'Todos os posts'
    url    = '/posts/'
    weight = 10

  [[languages.pt.menu.main]]
    parent = 'Blog'
    name   = 'Tags'
    url    = '/tags/'
    weight = 20

[[languages.en.menu.main]]
  name  = 'Blog'
  url   = '/en/blog/'
  weight = 20

  [[languages.en.menu.main]]
    parent = 'Blog'
    name   = 'All posts'
    url    = '/en/posts/'
    weight = 10

  [[languages.en.menu.main]]
    parent = 'Blog'
    name   = 'Tags'
    url    = '/en/tags/'
    weight = 20

[[languages.en.menu.main]]
  name  = 'Blog'
  url   = '/en/blog/'
  weight = 20

  [[languages.en.menu.main]]
    parent = 'Blog'
    name   = 'All posts'
    url    = '/en/posts/'
    weight = 10

  [[languages.en.menu.main]]
    parent = 'Blog'
    name   = 'Series'
    url    = '/en/categories/series/'
    weight = 20

  [[languages.en.menu.main]]
    parent = 'Blog'
    name   = 'Tags'
    url    = '/en/tags/'
    weight = 30
